setwd("C:/exploratory/ExData_Plotting1")
data <- read.csv("household_power_consumption.txt", sep=";", na.strings="?", stringsAsFactors=FALSE)

data$Time <- strptime(paste(data$Date, data$Time), "%d/%m/%Y %H:%M:%S")
data$Date <- as.Date(data$Date, "%d/%m/%Y")
data <- subset(data, data$Date == "2007-02-01" | data$Date == "2007-02-02")

png(file="plot4.png",width=480,height=480)
par(mfcol=c(2,2))
plot(data$Time, data$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
plot(data$Time, data$Sub_metering_1, type = "l", col = "black", xlab = "", ylab = "Energy sub metering")
lines(data$Time, data$Sub_metering_2, col = "red")
lines(data$Time, data$Sub_metering_3, col = "blue")
legend("topright", col = c("black", "red", "blue"), lty = 1, bty = "n", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(data$Time, data$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(data$Time, data$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()
